// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNxWQsLlhcRaYTpcE0MZsct5jikqPRTR8',
    appId: '1:1074023990435:web:0ea62d27a80666ef56ab16',
    messagingSenderId: '1074023990435',
    projectId: 'haradhaniya-f828c',
    authDomain: 'haradhaniya-f828c.firebaseapp.com',
    storageBucket: 'haradhaniya-f828c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJOzUr-D6Pmck9tnpimgfqmZvOmcp1D8o',
    appId: '1:1074023990435:android:1f2698ab4d71ee3856ab16',
    messagingSenderId: '1074023990435',
    projectId: 'haradhaniya-f828c',
    storageBucket: 'haradhaniya-f828c.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNxWQsLlhcRaYTpcE0MZsct5jikqPRTR8',
    appId: '1:1074023990435:web:563a08b22746805f56ab16',
    messagingSenderId: '1074023990435',
    projectId: 'haradhaniya-f828c',
    authDomain: 'haradhaniya-f828c.firebaseapp.com',
    storageBucket: 'haradhaniya-f828c.appspot.com',
  );
}