// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiV0NvoFXQ6hVtCXCB8Tv9BNGlrU8QZio',
    appId: '1:445085394060:web:07604933c94769580687a9',
    messagingSenderId: '445085394060',
    projectId: 'dfile-48084',
    authDomain: 'dfile-48084.firebaseapp.com',
    storageBucket: 'dfile-48084.appspot.com',
    measurementId: 'G-1HZF055BVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUgeODyI0EkAOMhszxJ8dVOpwIRA-6bMw',
    appId: '1:445085394060:android:c5b3cdaea09777110687a9',
    messagingSenderId: '445085394060',
    projectId: 'dfile-48084',
    storageBucket: 'dfile-48084.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQtV1zJJJXfRGCZlRHg2JsWiugWccQ5E0',
    appId: '1:445085394060:ios:9f9f392a6f8cd7290687a9',
    messagingSenderId: '445085394060',
    projectId: 'dfile-48084',
    storageBucket: 'dfile-48084.appspot.com',
    androidClientId: '445085394060-4q92vbl5rboaqk0k3i7052aj8b1iujsp.apps.googleusercontent.com',
    iosClientId: '445085394060-tauh6pa792d06rvbeo062ftee3jec5co.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenSultan',
  );

}